% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\usepackage{calligra}
\usepackage{ragged2e}
\justifying
\usepackage{tocbibind}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\begin{titlepage}
\begin{center}
\vspace*{\baselineskip}

{\bf\fontsize{19}{0}{\selectfont{ UNIVERSIDAD NACIONAL   AGRARIA \\ [0.5cm] LA MOLINA}}\\[0.5cm]
\fontsize{10}{0}{DEPARTAMENTO ACADÉMICO ESTADÍSTICA E INFORMÁTICA}\\ [0.5cm]
\bf\fontsize{14}{0}{\selectfont{ CARRERA PROFESIONAL DE ESTADÍSTICA E INFORMÁTICA}}
}\\[0.5cm]
\end{center}
\begin{center}
\vspace*{0.3in}
\begin{figure}[htb]
\begin{center}
\includegraphics[width=4.2cm,height=5cm]{imagen.jpg}
\end{center}
\end{figure}
\vspace*{0.1in}
\begin{Large}
\textbf{Prueba t de student para \\  muestras independientes } \\
\end{Large}
\vspace{0.4cm}
\begin{large}

\begin{center}
\textbf{Integrantes:}

\begin{tabbing}
    \hspace{2cm} Estrella Guerra, Danilo David \quad \= \quad         20220763 \\
    \hspace{2cm} Gómez Vigo, Héctor Estéfano   \quad \= \quad      20230397 \\
    \hspace{2cm} Montufar Paiva, Yeraldi Mercedes \quad  20230400 \\
    \hspace{2cm} Rojas Taco, Fabiana Romina    \quad \= \quad      20220956 \\
    \hspace{2cm} Zavala Malpartida, Kay Daniela L. \quad 20230420 \\
\end{tabbing}

\end{center}

\end{large}

\vspace*{0.2in}
\begin{large}
\textbf{Profesor:} \\
\end{large}
\vspace*{0.01in}

\begin{large}
Mg. Samuel HUAMANÍ  FLORES\\ [0.4cm]
\end{large}


\vspace*{0.3in}
\begin{large}
\textbf{LIMA-PERÚ }\\ [0.5cm]
\textbf{2024}
\end{large}
\end{center}
\end{titlepage}

\newpage

\renewcommand{\contentsname}{Indice de Contenido}

\tableofcontents

\newpage

\section*{Introducción}\label{introducciuxf3n}
\addcontentsline{toc}{section}{Introducción}

La educación es uno de los pilares que sostienen la base de una sociedad
justa y equitativa. Esto significa que el acceso a una educación
secundaria adecuada es uno de los factores que realmente importan en el
desarrollo personal y profesional de un adolescente. Este es uno de los
mayores desafíos y las principales inequidades persistentes en el Perú,
considerando el acceso y la calidad de la educación. El Estado aquí ha
tratado de poner en acción varias políticas para mejorar la cobertura y
la calidad de la educación; sin embargo, la brecha se muestra claramente
entre las áreas rurales y urbanas. Según UNICEF, un poco más de un
tercio de todos los niños de las áreas rurales de los países en
desarrollo logran alcanzar los niveles mínimos de competencia en las
competencias básicas de lectura y matemáticas, lo que refleja
profundamente las profundas desigualdades del sistema educativo. Esto es
particularmente relevante para una región como Ayacucho, donde las
barreras geográficas, sociales y económicas tienen impactos adversos en
el rendimiento escolar.

Ayacucho, una región con una historia marcada por conflictos y
desigualdades, ha mostrado avances en matrícula y retención escolar en
secundaria entre 2007 y 2015. Sin embargo, persisten disparidades
significativas en el rendimiento académico, especialmente entre las
áreas rurales y urbanas. En el ámbito rural, los estudiantes enfrentan
múltiples desafíos: acceso limitado a materiales educativos,
infraestructura escolar deficiente y carencias en la capacitación del
personal docente. Estas dificultades restringen el aprendizaje de
calidad y limitan el desarrollo del potencial de los jóvenes.

Es importante destacar que la educación no sólo empodera a los
individuos, sino que también tiene implicaciones profundas para el
crecimiento económico y social de las comunidades. En una región
predominantemente rural como Ayacucho, las barreras educativas perpetúan
el ciclo de pobreza y restringen las oportunidades de progreso. La
relación entre el nivel educativo y el desarrollo regional está bien
documentada. Muchos autores coinciden en que la inversión en educación
es crucial para combatir la pobreza y promover un crecimiento
sostenible. Según Perú (2016), las desigualdades actuales en la calidad
educativa entre entornos rurales y urbanos niegan a los niños y jóvenes
las mismas oportunidades, exigiendo una acción inmediata para corregir
esta situación.

Con estos antecedentes, el presente estudio se centrará principalmente
en el análisis del nivel de educación en el segundo ciclo de la
educación secundaria en Ayacucho, distinguiendo entre las zonas urbanas
y rurales. El objetivo general del presente estudio es identificar
disparidades generales llamativas en el logro de aprendizaje y los
factores que las explican. Como tal, esta investigación podría servir
para proporcionar una visión mucho más clara de la situación de la
educación en Ayacucho y poder sugerir recomendaciones que apoyen la
mejora de las condiciones educativas para las áreas más vulnerables
dentro de la provincia.

\newpage

\section*{Planteamiento del Problema}\label{planteamiento-del-problema}
\addcontentsline{toc}{section}{Planteamiento del Problema}

La educación en Perú sigue enfrentando grandes desafíos, particularmente
en relación con la desigualdad de género, lo cual afecta tanto el acceso
como la calidad del aprendizaje en diversas regiones, incluidas aquellas
más vulnerables como Ayacucho. Si bien se ha avanzado en la cobertura
educativa, las brechas de género continúan siendo un obstáculo
significativo. Según el informe del Instituto Nacional de Estadística e
Informática (2021), ``las mujeres mantuvieron una tasa de asistencia
ligeramente superior a la de los hombres a lo largo del periodo
2010-2020'' (p.~284), pero esta tendencia oculta problemas más profundos
relacionados con la percepción social de los roles de género, el acceso
limitado a oportunidades educativas y el predominio de estereotipos que
relegan a las niñas a campos educativos considerados tradicionalmente
``femeninos''. En el caso de Ayacucho, estos factores se ven exacerbados
por la pobreza y las condiciones socioeconómicas que enfrentan las
comunidades rurales, lo que crea un panorama de desigualdad no solo
entre géneros, sino también en términos de la calidad de la educación
recibida. A pesar de que las mujeres acceden en mayor número a la
educación secundaria, la calidad de la misma sigue siendo desigual, lo
que perjudica las oportunidades de desarrollo académico de las
estudiantes, especialmente en contextos rurales.

Este contexto de desigualdad de género en la educación requiere una
intervención política específica que aborde las barreras estructurales y
culturales que perpetúan las disparidades. Según la Perú (2016),
millones de niñas en el mundo no tienen acceso a una educación de
calidad en igualdad de condiciones, y Ayacucho no es la excepción. Esto,
como lo señala la organización, es ``una violación de la Convención
sobre los Derechos del Niño'' (p.~28), al privar a las niñas de las
mismas oportunidades que los niños para acceder a una educación completa
y de calidad. Es crucial que las políticas públicas promuevan la equidad
de género en la educación, garantizando tanto la asistencia como la
permanencia de las estudiantes, para que puedan desarrollar su potencial
sin limitaciones basadas en su sexo. El estudio de las disparidades de
género en la educación de Ayacucho es fundamental para entender cómo las
diferencias entre hombres y mujeres afectan el rendimiento académico y
el acceso a oportunidades educativas. Abordar estas desigualdades no
solo implica mejorar las infraestructuras educativas o aumentar la
cobertura, sino también garantizar que las niñas y los niños tengan un
trato igualitario desde el ámbito educativo, eliminando barreras de
acceso, contenidos discriminatorios y apoyando el desarrollo profesional
de las estudiantes en todos los campos, sin restricciones de género. Las
políticas públicas deben ser sensibles a estas realidades y diseñar
intervenciones específicas que permitan un acceso equitativo a la
educación para todos los niños y niñas, independientemente de su género.

\subsection*{Preguntas de
investigación}\label{preguntas-de-investigaciuxf3n}
\addcontentsline{toc}{subsection}{Preguntas de investigación}

\subsubsection*{Pregunta General}\label{pregunta-general}
\addcontentsline{toc}{subsubsection}{Pregunta General}

¿Existe una diferencia significativa en el rendimiento académico en
matemáticas entre los estudiantes de sexo femenino y masculino en las
zonas rurales de Ayacucho?

\subsubsection*{Preguntas Específicas}\label{preguntas-especuxedficas}
\addcontentsline{toc}{subsubsection}{Preguntas Específicas}

\begin{center}

\justify
\begin{enumerate}
    \item ¿Es el promedio de las notas en matemáticas de los estudiantes hombres menor o igual al promedio de las estudiantes mujeres en las zonas rurales de Ayacucho?
    \item ¿Existen diferencias en las proporciones de aprobados en matemáticas entre mujeres y hombres en la zona rural de Ayacucho?
    \item ¿Es el promedio de las notas en matemáticas de los estudiantes hombres al menos 15 puntos mayor que el promedio de las estudiantes mujeres en las zonas rurales de Ayacucho?  
    
\end{enumerate}

\end{center}

\section*{Marco teórico}\label{marco-teuxf3rico}
\addcontentsline{toc}{section}{Marco teórico}

\subsection*{La Prueba t para Muestras Independientes en el Análisis de
las Diferencias por
Género}\label{la-prueba-t-para-muestras-independientes-en-el-anuxe1lisis-de-las-diferencias-por-guxe9nero}
\addcontentsline{toc}{subsection}{La Prueba t para Muestras
Independientes en el Análisis de las Diferencias por Género}

La prueba t para muestras independientes es una herramienta estadística
utilizada para comparar las medias de dos grupos independientes y
determinar si las diferencias observadas son estadísticamente
significativas Team (2024). En este estudio, se aplicará para evaluar si
existen diferencias significativas en las calificaciones promedio de
hombres y mujeres en el segundo año de secundaria de las zonas rurales
de Ayacucho. Este método permite discernir si las disparidades
observadas son lo suficientemente grandes como para descartar la
posibilidad de que sean producto del azar.

\vspace{0.5cm}

\subsection*{Supuestos de la prueba t}\label{supuestos-de-la-prueba-t}
\addcontentsline{toc}{subsection}{Supuestos de la prueba t}

Para que la prueba t sea válida, deben cumplirse los siguientes
supuestos:

\subsubsection*{Independencia de las
observaciones}\label{independencia-de-las-observaciones}
\addcontentsline{toc}{subsubsection}{Independencia de las observaciones}

Las muestras deben ser independientes entre sí, es decir, los
participantes de un grupo no deben influir en los participantes del otro
grupo Cohen (1988).

\subsubsection*{Normalidad}\label{normalidad}
\addcontentsline{toc}{subsubsection}{Normalidad}

Las calificaciones deben estar distribuidas aproximadamente de manera
normal en ambos grupos. Esto se puede verificar mediante:

\begin{itemize}
\item
  Prueba de normalidad de Shapiro-Wilk o Kolmogorov-Smirnov.
\item
  Métodos gráficos como histogramas y diagramas de caja (boxplots) Field
  (2013).
\end{itemize}

\subsection*{Fórmula de la prueba t}\label{fuxf3rmula-de-la-prueba-t}
\addcontentsline{toc}{subsection}{Fórmula de la prueba t}

\[
t = \frac{X_1 - X_2}{\sqrt{\frac{S_c^2}{n_1} + \frac{S_c^2}{n_2}}}\sim t_{n_{1}+n_{2}-2}
\]

Donde:

\begin{itemize}
    \item $X_1$ y $X_2$ son las medias de los grupos urbano y rural.
    \item $S_c^2$ y $S_c^2$ representan las varianzas de las calificaciones.
    \item $n_1$ y $n_2$ son los tamaños muestrales de cada grupo.
\end{itemize}

Este análisis permitirá validar o rechazar la hipótesis nula, que
establece que no existen diferencias significativas entre las
calificaciones promedio de hombres y mujeres. Si el valor calculado de t
excede el valor crítico, se aceptará la hipótesis alternativa, indicando
que existen diferencias significativas.

\subsection*{Diferencias de Género en el Rendimiento Académico en Zonas
Rurales}\label{diferencias-de-guxe9nero-en-el-rendimiento-acaduxe9mico-en-zonas-rurales}
\addcontentsline{toc}{subsection}{Diferencias de Género en el
Rendimiento Académico en Zonas Rurales}

\vspace{0.5cm}

Las diferencias en las calificaciones entre hombres y mujeres en las
zonas rurales pueden atribuirse a una combinación de factores
socioculturales, económicos, familiares y educativos que influyen de
manera diferenciada en su rendimiento académico. A continuación, se
detallan algunas de las razones más relevantes:

\subsubsection{Expectativas de Roles de
Género:}\label{expectativas-de-roles-de-guxe9nero}

En las comunidades rurales, los roles tradicionales asignados a hombres
y mujeres pueden influir en el tiempo y el esfuerzo que cada género
dedica a los estudios. Las niñas suelen asumir mayores responsabilidades
domésticas, como el cuidado de hermanos menores, la limpieza y la
preparación de alimentos. Estas tareas reducen significativamente el
tiempo disponible para el estudio y la realización de tareas escolares
La República (2021).

\subsubsection{Acceso Desigual a Recursos
Educativos:}\label{acceso-desigual-a-recursos-educativos}

Las familias en situación de pobreza extrema priorizan con frecuencia la
educación de los varones debido a percepciones culturales que asocian a
los hombres con futuros proveedores económicos del hogar. Esto puede
llevar a una inversión desigual en materiales educativos, transporte y
otros recursos que impactan en el desempeño escolar de las niñas UNICEF
(2021).

\subsubsection{Desnutrición y Salud:}\label{desnutriciuxf3n-y-salud}

Las condiciones de pobreza en las zonas rurales afectan de manera
diferenciada a niñas y niños. La desnutrición crónica, más frecuente en
niñas debido a prácticas discriminatorias en la distribución de
alimentos en el hogar, impacta negativamente en su capacidad de
concentración y aprendizaje, lo que se traduce en un menor rendimiento
académico Instituto Nacional de Estadística e Informática (2021).

\subsubsection{Desafíos
Lingüísticos:}\label{desafuxedos-linguxfcuxedsticos}

En regiones como Ayacucho, donde el quechua es la lengua materna
predominante, las niñas enfrentan mayores barreras para el aprendizaje
del castellano debido a su menor exposición a contextos fuera del hogar.
Esta falta de dominio del idioma oficial afecta su desempeño en materias
clave como comprensión lectora y matemáticas Cueto (2004).

\subsubsection{Deserción Escolar y Matrimonio
Temprano:}\label{deserciuxf3n-escolar-y-matrimonio-temprano}

Las niñas en zonas rurales tienen una mayor probabilidad de abandonar la
escuela debido a presiones familiares y sociales relacionadas con el
matrimonio temprano y la maternidad adolescente. Estas prácticas limitan
sus oportunidades de continuar con sus estudios y afectan sus
calificaciones durante el tiempo que permanecen en el sistema educativo
{[}UNESCO, 2020{]}.

\subsubsection{Infraestructura y Seguridad
Escolar:}\label{infraestructura-y-seguridad-escolar}

La falta de instalaciones escolares adecuadas, como baños separados por
género, puede disuadir a las niñas de asistir regularmente a la escuela,
especialmente durante la menstruación. Esta falta de asistencia regular
influye directamente en su rendimiento académico Tarea.org.pe (2021).

\section*{Objetivos}\label{objetivos}
\addcontentsline{toc}{section}{Objetivos}

\subsection*{Objetivo general}\label{objetivo-general}
\addcontentsline{toc}{subsection}{Objetivo general}

\vspace{0.25cm}

Determinar si existe una diferencia significativa en el rendimiento
académico en matemáticas entre hombres y mujeres en zonas rurales de
Ayacucho utilizando la prueba t para muestras independientes.

\subsection*{Objetivos específicos}\label{objetivos-especuxedficos}
\addcontentsline{toc}{subsection}{Objetivos específicos}

\vspace{0.5cm}

\begin{itemize}
    \item Comparar si el promedio de las notas en matemáticas de los estudiantes hombres es mayor al promedio de las estudiantes mujeres en zonas rurales de Ayacucho, aplicando la prueba t de Student.
    \item Se desea determinar si existe una diferencia significativa entre las proporciones de estudiantes aprobados en matemáticas entre mujeres y hombres en zonas rurales de Ayacucho.
    \item Evaluar la magnitud de la diferencia en las notas promedio de matemáticas entre hombres y mujeres en este contexto rural.
    \item Identificar cómo las condiciones socioeconómicas y educativas influyen de manera diferenciada en el rendimiento académico de hombres y mujeres en matemáticas.
    \item Proponer estrategias educativas orientadas a reducir las brechas de género en el rendimiento académico en matemáticas en zonas rurales de Ayacucho.
\end{itemize}

\section*{Hipótesis}\label{hipuxf3tesis}
\addcontentsline{toc}{section}{Hipótesis}

\subsection*{Hipótesis general}\label{hipuxf3tesis-general}
\addcontentsline{toc}{subsection}{Hipótesis general}

\begin{itemize}
    \item \textbf{H$_{0}$:} EEl rendimiento académico promedio en el área de matemáticas de los estudiantes de sexo femenino es igual al de los estudiantes de sexo masculino en zonas rurales de Ayacucho.

  \item \textbf{H$_{1}$:} El rendimiento académico promedio en el área de matemáticas de los estudiantes de sexo femenino es diferente al de los estudiantes de sexo masculino en zonas rurales de Ayacucho.

\end{itemize}

\subsection*{Hipótesis específicas}\label{hipuxf3tesis-especuxedficas}
\addcontentsline{toc}{subsection}{Hipótesis específicas}

\begin{enumerate}
    \item \textbf{Hipótesis 1:}
    \begin{itemize}
        \item \textbf{H$_{0}$:} El promedio de las notas en matemáticas de los estudiantes hombres es menor o igual al promedio de las estudiantes mujeres en zonas rurales de Ayacucho.
        \item \textbf{H$_{1}$:} El promedio de las notas en matemáticas de los estudiantes hombres es mayor al promedio de las estudiantes mujeres en zonas rurales de Ayacucho.
    \end{itemize}
    \item \textbf{Hipótesis 2:}
    \begin{itemize}
        \item \textbf{H$_{0}$:} Las proporciones de aprobados entre mujeres y hombres en la zona rural de Ayacucho son iguales.
        \item \textbf{H$_{1}$:} Las proporciones de aprobados entre mujeres y hombres en la zona rural de Ayacucho son diferentes.
    \end{itemize}
    \item \textbf{Hipótesis 3:}
    \begin{itemize}
        \item \textbf{H$_{0}$:} El promedio de las notas en matemáticas de las estudiantes mujeres es menor o igual al promedio de los estudiantes hombres en 15 puntos en zonas rurales de Ayacucho.
        \item \textbf{H$_{1}$:} El promedio de las notas en matemáticas de los estudiantes hombres es menor en más de 15 puntos que el promedio de las estudiantes mujeres en zonas rurales de Ayacucho.
    \end{itemize}
\end{enumerate}

\section*{Metodología}\label{metodologuxeda}
\addcontentsline{toc}{section}{Metodología}

\subsection*{Operacionalización de
variables}\label{operacionalizaciuxf3n-de-variables}
\addcontentsline{toc}{subsection}{Operacionalización de variables}

A continuación, se describen las principales variables del estudio,
indicando su significado y las formas en que serán medidas o
categorizadas.

\begin{itemize}
    \item sexo: Sexo del estudiante. Variable categórica con dos alternativas: masculino. Alternativas: Hombre, Mujer
    \item departamento: Departamento. Variable cualitativa que representa la región administrativa a la que pertenece la institución.
    \item M500-EM-2S-2023-MA: Medida en matemáticas. Variable cuantitativa que refleja el puntaje obtenido por los estudiantes en la evaluación de matemáticas.

\end{itemize}

\subsection*{Población}\label{poblaciuxf3n}
\addcontentsline{toc}{subsection}{Población}

La población de este estudio está constituida por todas las
instituciones educativas de la región de Ayacucho que imparten educación
básica regular.

Esto incluye escuelas públicas y privadas que presentan características
similares en términos de gestión y nivel educativo. La población se
delimita temporalmente al año académico 2023, lo que permite una
evaluación actualizada y pertinente del nivel educativo en el área de
matemáticas.

\subsubsection*{Normalidad de la
población}\label{normalidad-de-la-poblaciuxf3n}
\addcontentsline{toc}{subsubsection}{Normalidad de la población}

Primero debemos de comprobar que nuestra población sigue una
distribución normal.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{BD }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"BD\_2S ENLA muestral 2023.xlsx"}\NormalTok{)}

\NormalTok{data\_rural }\OtherTok{\textless{}{-}}\NormalTok{ BD }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(departamento }\SpecialCharTok{==} \StringTok{"AYACUCHO"}\NormalTok{, area }\SpecialCharTok{==} \StringTok{"Rural"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"sexo"}\NormalTok{, }\StringTok{"M500\_EM\_2S\_2023\_MA"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{na.omit}\NormalTok{()}

\FunctionTok{shapiro.test}\NormalTok{(data\_rural}\SpecialCharTok{$}\NormalTok{M500\_EM\_2S\_2023\_MA)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  data_rural$M500_EM_2S_2023_MA
## W = 0.9864, p-value = 2.823e-06
\end{verbatim}

Según el criterio de p\_valor, la población no sigue una distribución
normal.\\
Para detectar posibles datos atipicos vamos a usar el método z-score.

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  data_rural_sin$M500_EM_2S_2023_MA
## W = 0.998, p-value = 0.5628
\end{verbatim}

Nuevamente usando el test de \texttt{Shapiro-wilk} y por el criterio de
p\_valor comprobamos que el

\[p_{valor}=0.5628>\alpha=0.05\]\\
y se verifica que nuestra población ahora sigue una distribución normal.

\begin{center}\includegraphics{trabajo_final_analisis-estadistico_files/figure-latex/unnamed-chunk-3-1} \end{center}

\subsection*{Muestra}\label{muestra}
\addcontentsline{toc}{subsection}{Muestra}

El uso de un diseño de muestreo estratificado permite dividir la
población en dos estratos claramente diferenciados: el masculino y el
femenino. Esta división se hace con el objetivo de que ambos génneros
estén justamente representados en la muestra, ya que se espera que sus
niveles de logros educativos sean similares.

Dentro de cada estrato, se realizará un muestreo aleatorio simple para
seleccionar a los estudiantes. De esta manera, se mantendrá la
aleatoriedad y se evitarán sesgos dentro de cada subgrupo.

\subsubsection*{Tamaño de la muestra}\label{tamauxf1o-de-la-muestra}
\addcontentsline{toc}{subsubsection}{Tamaño de la muestra}

Determinamos el tamaño de la muestra total por muestreo estratificado
(n) en 160 estudiantes.

Separamos nuestra población en dos estratos, ``masculino'' y
``femenino''.

Luego procedemos a estimar el tamaño de cada muestra de cada estrato.

\[n_{mujer}= n*\frac{N_{mujer}}{N}, \quad n_{hombre}= n*\frac{N_{hombre}}{N}, \quad \]

\begin{itemize}
    \item N: tamaño de la población 
    \item n: tamaño total de la muestra
    \item $N_{mujer}$: tamaño de la población solo de mujeres
    \item $N_{hombre}$: tamaño de la población solo de hombres
    \item $n_{mujer}$: tamaño de la muestra de mujeres
    \item $n_{hombre}$: tamaño de la muestra de hombre

\end{itemize}

\subsubsection*{Varianzas poblacionales}\label{varianzas-poblacionales}
\addcontentsline{toc}{subsubsection}{Varianzas poblacionales}

Para realizar la prueba t de Student para muestras independientes, es
necesario primero verificar si las varianzas poblacionales son iguales o
diferentes. Con un nivel de significancia del 5\%, se llevará a cabo una
prueba de hipótesis para determinar si las varianzas de las dos
poblaciones son iguales o no.

\begin{table}[!h]
\centering
\caption{\label{tab:Estadisticas generos}Resumen de las notas por género}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
sexo & Media (\(\mu\)) & Varianza (\(\sigma^{2}\)) & Desviación Estándar (\(\sigma\)) & Tamaño de la población (\(N\))\\
\midrule
\cellcolor{gray!10}{Hombre} & \cellcolor{gray!10}{549.3282} & \cellcolor{gray!10}{4936.985} & \cellcolor{gray!10}{70.26368} & \cellcolor{gray!10}{342}\\
Mujer & 538.1761 & 4700.335 & 68.55899 & 380\\
\bottomrule
\end{tabular}
\end{table}

\begin{enumerate}
  \item \textbf{Hipótesis nula y alternativa:}
    \[
    H_0: \sigma^2_{\text{mujer}} = \sigma^2_{\text{hombre}}
    \]
    \[
    H_1: \sigma^2_{\text{mujer}} \neq \sigma^2_{\text{hombre}}
    \]
  \item \textbf{Nivel de significancia:}
    \[
    \alpha = 0.05
    \]

  \item \textbf{Estadístico de prueba:}
    \[
    F_k = \frac{S^2_{\text{mujer}}}{S^2_{\text{hombre}}}, \quad F_{84, 76}
    \]

  \item \textbf{Región crítica:}
    \begin{figure}[ht]
        \centering
        \begin{tikzpicture}
            \begin{axis}[
                domain=0:4,
                samples=200,
                xlabel={$F$},
                ylabel={Densidad},
                ymin=0,
                ymax=0.45,
                axis lines=left,
                legend pos=north east,
                title={Distribución F con Región Crítica (dos colas)}
            ]
                % Curva de la distribución F
                \addplot[blue, thick] {((x^2) * exp(-x^2/2) / sqrt(2*pi))};
                \addlegendentry{Distribución F}

                % Región crítica a la izquierda (F < -1.96)
                \addplot [
                    domain=0:0.643,
                    samples=100,
                    fill=red,
                    opacity=0.4,
                ] {((x^2) * exp(-x^2/2) / sqrt(2*pi))} \closedcycle;
                \addlegendentry{Región Crítica Izquierda}

                % Región crítica a la derecha (F > 1.96)
                \addplot [
                    domain=1.564:4,
                    samples=100,
                    fill=red,
                    opacity=0.4,
                ] {((x^2) * exp(-x^2/2) / sqrt(2*pi))} \closedcycle;
                \addlegendentry{Región Crítica Derecha}

                % Línea vertical en Z = 0.643
                \addplot[red, dashed] coordinates {(0.643, 0) (0.643, 0.1)};
                \node at (axis cs:0.643,0.13) [anchor=north east, blue] {0.643};

                % Línea vertical en F = 1.564
                \addplot[red, dashed] coordinates {(1.564, 0) (1.564, 0.1)};
                \node at (axis cs:1.564,0.13) [anchor=north west, blue] {1.564};

                % Línea vertical en F = 1.012
                \addplot[black, dashed] coordinates {(1.012, 0) (1.012, 0.15)};
                \node at (axis cs:1.012,0.18) [anchor=north east] {1.012};
            \end{axis}
        \end{tikzpicture}
        \caption{Gráfico de la distribución F con regiones críticas.}
    \end{figure}  
   \[
    RC = F_k < 0.643 \quad \text{o} \quad F_k > 1.564
    \]

  \item \textbf{Cálculo del estadístico:}
    \[
    F_k = \frac{77.12865}{76.70822} = 1.012
    \]

  \item \textbf{Decisión:}
    \[
    F_k = 1.012 \notin RC \quad \text{por lo que no se rechaza } H_0
    \]

  \item \textbf{Conclusión:}
    Con un nivel de significancia del 5\% se puede afirmar que las varianzas poblacionales de los estudiantes hombres y mujeres son iguales.
\end{enumerate}

\subsubsection*{Homogeneidad de Varianzas usando
Bartlett}\label{homogeneidad-de-varianzas-usando-bartlett}
\addcontentsline{toc}{subsubsection}{Homogeneidad de Varianzas usando
Bartlett}

\[H_{0}: \text{Las varianzas de las notas entre hombres y mujeres son iguales.}\]\\
\[H_{0}: \text{Las varianzas de las notas entre hombres y mujeres son diferentes.}\]

\begin{verbatim}
## 
##  Bartlett test of homogeneity of variances
## 
## data:  data_rural_sin$M500_EM_2S_2023_MA by data_rural_sin$sexo
## Bartlett's K-squared = 0.21642, df = 1, p-value = 0.6418
\end{verbatim}

Dado que \(p_{valor}=0.6418>\alpha=0.05\), no se rechaza la hipótesis
nula. Esto implica que no hay evidencia estadísticamente significativa
para afirmar que las varianzas de las notas entre hombres y mujeres son
diferentes.

\begin{center}\includegraphics{trabajo_final_analisis-estadistico_files/figure-latex/unnamed-chunk-6-1} \end{center}

\subsection*{Procedimiento}\label{procedimiento}
\addcontentsline{toc}{subsection}{Procedimiento}

\subsubsection*{Desarrollo de la Hipótesis
General}\label{desarrollo-de-la-hipuxf3tesis-general}
\addcontentsline{toc}{subsubsection}{Desarrollo de la Hipótesis General}

Se desea determinar si existe una diferencia estadísticamente
significativa en las notas promedio de matemáticas entre estudiantes
mujeres y hombres en zonas rurales de Ayacucho. Con un nivel de
significancia del 5\%, se cuenta con los siguientes datos muestrales:

\subsubsection*{Extracción de la
muestra}\label{extracciuxf3n-de-la-muestra}
\addcontentsline{toc}{subsubsection}{Extracción de la muestra}

En este paso usaremos el paquete \texttt{teachingsamplig} para extraer
nuestras muestras.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(TeachingSampling)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{sam }\OtherTok{\textless{}{-}} \FunctionTok{S.STSI}\NormalTok{(data\_rural\_sin}\SpecialCharTok{$}\NormalTok{sexo, }\FunctionTok{c}\NormalTok{(N\_h, N\_m), }\FunctionTok{c}\NormalTok{(n\_h, n\_m))}
\NormalTok{muestra }\OtherTok{\textless{}{-}}\NormalTok{ data\_rural\_sin[sam,]}

\NormalTok{muestra\_hombre }\OtherTok{\textless{}{-}}\NormalTok{ muestra }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(sexo }\SpecialCharTok{==} \StringTok{"Hombre"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\DecValTok{2}\NormalTok{)}
\NormalTok{muestra\_mujer }\OtherTok{\textless{}{-}}\NormalTok{ muestra }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(sexo }\SpecialCharTok{==} \StringTok{"Mujer"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\caption{\label{tab:tablasss}Resumen de cada muestra}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
sexo & Media (\(\bar{x}\)) & Varianza (\(s^{2}\)) & Desviación Estándar (\(s\)) & Tamaño (\(n\))\\
\midrule
\cellcolor{gray!10}{Hombre} & \cellcolor{gray!10}{553.216} & \cellcolor{gray!10}{5884.149} & \cellcolor{gray!10}{76.708} & \cellcolor{gray!10}{76}\\
Mujer & 538.551 & 5948.829 & 77.129 & 84\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
    \item \textbf{H$_{0}$:} EEl rendimiento académico promedio en el área de matemáticas de los estudiantes de sexo femenino es igual al de los estudiantes de sexo masculino en zonas rurales de Ayacucho.

  \item \textbf{H$_{1}$:} El rendimiento académico promedio en el área de matemáticas de los estudiantes de sexo femenino es diferente al de los estudiantes de sexo masculino en zonas rurales de Ayacucho.

\end{itemize}

\begin{enumerate}
  \item \textbf{Hipótesis nula y alternativa:}
    \[
    H_0: \mu_{\text{mujer}} = \mu_{\text{hombre}}
    \]
    \[
    H_1: \mu_{\text{mujer}} \neq \mu_{\text{hombre}}
    \]

  \item \textbf{Nivel de significancia:}
    \[
    \alpha = 0.05
    \]

  \item \textbf{Estadístico de prueba:}
    \[
    t = \frac{\bar{X}_{\text{mujer}} - \bar{X}_{\text{hombre}} - (\mu_{\text{mujer}} - \mu_{\text{hombre}})}{\sqrt{\frac{S_c^2}{n_{\text{mujer}}} + \frac{S_c^2}{n_{\text{hombre}}}}}, \quad t \sim t_{n_{\text{mujer}} + n_{\text{hombre}} - 2}
    \]
    \textbf{Cálculo de la desviación estándar agrupada:}
    \[
    S_c = \sqrt{\frac{(n_{\text{mujer}} - 1) S_{\text{mujer}}^2 + (n_{\text{hombre}} - 1) S_{\text{hombre}}^2}{n_{\text{mujer}} + n_{\text{hombre}} - 2}}
    \]

  \item \textbf{Región Crítica:}
    \begin{figure}[ht]
        \centering
        \begin{tikzpicture}
            \begin{axis}[
                domain=-4:4,
                samples=200,
                xlabel={$t$},
                ylabel={Densidad},
                ymin=0,
                ymax=0.45,
                axis lines=left,
                legend pos=north east,
                title={Distribución t con Región Crítica}
            ]
                % Curva de la distribución t
                \addplot[blue, thick] {exp(-x^2 / 2) / sqrt(2 * pi)};
                \addlegendentry{Distribución t}

                % Región crítica a la izquierda (t < -1.96)
                \addplot [
                    domain=-4:-1.96,
                    samples=100,
                    fill=red,
                    opacity=0.5,
                ] {exp(-x^2 / 2) / sqrt(2 * pi)} \closedcycle;
                \addlegendentry{Región Crítica Izquierda}

                % Región crítica a la derecha (t > 1.96)
                \addplot [
                    domain=1.96:4,
                    samples=100,
                    fill=red,
                    opacity=0.5,
                ] {exp(-x^2 / 2) / sqrt(2 * pi)} \closedcycle;
                \addlegendentry{Región Crítica Derecha}

                % Línea vertical en t = -1.975
                \addplot[red, dashed] coordinates {(-1.975, 0) (-1.975, 0.1)};
                \node at (axis cs:-1.975,0.13) [anchor=north east, blue] {-1.975};

                % Línea vertical en t = 1.975
                \addplot[red, dashed] coordinates {(1.975, 0) (1.975, 0.1)};
                \node at (axis cs:1.975,0.13) [anchor=north west, blue] {1.975};

                % Línea vertical en t = -1.2
                \addplot[black, dashed] coordinates {(-1.2, 0) (-1.2, 0.15)};
                \node at (axis cs:-1.2,0.18) [anchor=north east] {-1.2};
            \end{axis}
        \end{tikzpicture}
        \caption{Gráfico de la distribución t con regiones críticas.}
    \end{figure}
    \[
    t_{0.025, 158} = -1.975 \quad \text{y} \quad t_{0.975, 158} = 1.975
    \]
    \item \textbf{Cálculo del estadístico y grados de libertad:}
    \[
    S_c = \sqrt{\frac{(84 - 1) \cdot 77.12865^2 + (76 - 1) \cdot 76.70822^2}{158}} = 76.93
    \]
    \[
    t_k = \frac{538.5511 - 553.2158 - 0}{\sqrt{\frac{76.93^2}{84} + \frac{76.93^2}{76}}} = -1.2
    \]
    \item \textbf{Decisión:}
    \[
    t_k = -1.2 \notin RC \quad \text{por lo que se rechaza } H_0
    \]

  \item \textbf{Conclusión:}
    Con un nivel de significancia del 5\%, hay suficiente evidencia para afirmar que los estudiantes hombres y mujeres en las áreas rurales de Ayacucho tienen notas promedio diferentes en matemáticas. Es decir, la diferencia observada en las medias de las notas no es atribuible al azar, y existe una diferencia significativa en el rendimiento académico entre ambos géneros en esta región.
    
\end{enumerate}

\subsection*{Desarrollo de las Hipótesis
Específicas}\label{desarrollo-de-las-hipuxf3tesis-especuxedficas}
\addcontentsline{toc}{subsection}{Desarrollo de las Hipótesis
Específicas}

\subsubsection*{Los hombres superan a las mujeres en el promedio
general}\label{los-hombres-superan-a-las-mujeres-en-el-promedio-general}
\addcontentsline{toc}{subsubsection}{Los hombres superan a las mujeres
en el promedio general}

Se desea determinar si los estudiantes hombres tienen un rendimiento
académico promedio en matemáticas mayor que el de las estudiantes
mujeres en zonas rurales de Ayacucho. Con un nivel de significancia del
5\%, se cuenta con los siguientes datos muestrales:

\begin{enumerate}
  \item \textbf{Hipótesis nula y alternativa:}
    \[
    H_0: \mu_{\text{hombres}} \leq \mu_{\text{mujeres}}
    \]
    \[
    H_1: \mu_{\text{hombres}} > \mu_{\text{mujeres}}
    \]

  \item \textbf{Nivel de significancia:}
    \[
    \alpha = 0.05
    \]

  \item \textbf{Estadístico de prueba:}
    La fórmula del estadístico \(t\) para muestras independientes con varianzas iguales es:
    \[
    t = \frac{\bar{X}_{\text{hombres}} - \bar{X}_{\text{mujeres}}}{\sqrt{S_c^2 \left( \frac{1}{n_{\text{hombres}}} + \frac{1}{n_{\text{mujeres}}} \right)}}
    \]
    Donde:
    \[
    \bar{X}_{\text{hombres}} = 538.5511, \quad \bar{X}_{\text{mujeres}} = 553.2158
    \]
    \[
    n_{\text{hombres}} = 76, \quad n_{\text{mujeres}} = 84
    \]
    \[
    S_c = \sqrt{\frac{(n_{\text{hombres}} - 1) \cdot S_{\text{hombres}}^2 + (n_{\text{mujeres}} - 1) \cdot S_{\text{mujeres}}^2}{n_{\text{hombres}} + n_{\text{mujeres}} - 2}}
    \]
    Reemplazando los valores:
    \[
    S_c = \sqrt{\frac{(76 - 1) \cdot (76.7082)^2 + (84 - 1) \cdot (77.12865)^2}{76 + 84 - 2}} = \sqrt{5911.71}
    \]
    Ahora hallamos \(t\):
    \[
    t = \frac{538.5511 - 553.2158}{\sqrt{5911.71 \cdot \left( \frac{1}{76} + \frac{1}{84} \right)}} = \frac{-14.6647}{12.46} = -1.1765
    \]
  \item \textbf{Región crítica:}
    \begin{figure}[ht]
    \centering
    \begin{tikzpicture}
        \begin{axis}[
            domain=-4:4,
            samples=200,
            xlabel={Valores de \( t \)},
            ylabel={Densidad de probabilidad},
            ymin=0,
            ymax=0.45,
            axis lines=left,
            legend pos=north east,
            title={Distribución \( t \) de student para muestras independientes (una cola)}
        ]
            % Curva de la distribución t de student
            \addplot[blue, thick] {exp(-x^2 / 2) / sqrt(2 * pi)};
            \addlegendentry{Distribución \( t \)}

            % Región crítica (x >= 1.645)
            \addplot [
                domain=1.645:4,
                samples=100,
                fill=red,
                opacity=0.5,
            ] {exp(-x^2 / 2) / sqrt(2 * pi)} \closedcycle;
            \addlegendentry{Región Crítica}

            % Línea vertical en valor crítico (1.645)
            \addplot[brown, dashed, thick] coordinates {(1.645, 0) (1.645, 0.2)};
            \node at (axis cs:1.645,0.2) [anchor=north west, brown] {\( t = 1.645 \)};

            % Línea vertical en \( t \) calculado (-1.1765)
            \addplot[green, dashed, thick] coordinates {(-1.1765, 0) (-1.1765, 0.13)};
            \node at (axis cs:-0.010,0.13) [anchor=north east, black] {\( t_{k} = -1.1765 \)};
        \end{axis}
    \end{tikzpicture}
    \caption{Distribución \( t \) con región crítica y estadístico calculado.}
   \end{figure}
   \[
    RC = t > 1.65 \quad \text{(con } t_{0.05, 158} = 1.65\text{)}
    \]

  \item \textbf{Decisión:}
    Como \(t_k = -1.1765 \notin RC\), no se rechaza la hipótesis nula \(H_0\) al nivel de significancia del 5\%.

  \item \textbf{Conclusión:}
    No hay suficiente evidencia estadística para afirmar que el promedio de las notas de los hombres es mayor al de las mujeres en las zonas rurales de Ayacucho.
\end{enumerate}

\subsubsection*{La proporción de aprobados de hombres y mujeres son
diferentes}\label{la-proporciuxf3n-de-aprobados-de-hombres-y-mujeres-son-diferentes}
\addcontentsline{toc}{subsubsection}{La proporción de aprobados de
hombres y mujeres son diferentes}

\begin{enumerate}
  \item \textbf{Hipótesis nula y alternativa:}
    \[
    H_0: p_{\text{ma}} = p_{\text{ha}}
    \]
    \[
    H_1: p_{\text{ma}} \neq p_{\text{ha}}
    \]
    donde:
    \begin{itemize}
        \item \( p_{\text{ma}} \) es la proporción de estudiantes mujeres aprobadas en matemáticas.
        \item \( p_{\text{ha}} \) es la proporción de estudiantes hombres aprobados en matemáticas.
    \end{itemize}
    
  \item \textbf{Nivel de significancia:}
    \[
    \alpha = 0.05
    \]
    
  \item \textbf{Estadístico de prueba:}
    La fórmula del estadístico \(z\) para la prueba de dos proporciones es:
    \[
    z = \frac{p_{\text{ma}} - p_{\text{ha}}}{\sqrt{P(1 - P) \left( \frac{1}{n_1} + \frac{1}{n_2} \right)}}
    \]
    donde:
    \[
    P = \frac{x_1 + x_2}{n_1 + n_2}
    \]
    y los valores para las mujeres y hombres son:
    \[
    \text{Mujeres:} \quad n_1 = 84, \quad x_1 = 19, \quad p_{\text{ma}} = \frac{19}{84} \approx 0.2262
    \]
    \[
    \text{Hombres:} \quad n_2 = 76, \quad x_2 = 19, \quad p_{\text{ha}} = \frac{19}{76} \approx 0.2500
    \]
    Entonces, la proporción combinada \(P\) es:
    \[
    P = \frac{x_1 + x_2}{n_1 + n_2} = \frac{19 + 19}{84 + 76} = \frac{38}{160} = 0.2375
    \]

  \item \textbf{Región crítica:}
    \begin{figure}[ht]
        \centering
        \begin{tikzpicture}
            \begin{axis}[
                domain=-4:4,
                samples=200,
                xlabel={$Z$},
                ylabel={Densidad},
                ymin=0,
                ymax=0.45,
                axis lines=left,
                legend pos=north east,
                title={Distribución Z con Región Crítica}
            ]
                % Curva de la distribución normal estándar
                \addplot[blue, thick] {exp(-x^2 / 2) / sqrt(2 * pi)};
                \addlegendentry{Distribución Z}

                % Región crítica a la izquierda (Z < -1.96)
                \addplot [
                    domain=-4:-1.96,
                    samples=100,
                    fill=red,
                    opacity=0.5,
                ] {exp(-x^2 / 2) / sqrt(2 * pi)} \closedcycle;
                \addlegendentry{Región Crítica Izquierda}

                % Región crítica a la derecha (Z > 1.96)
                \addplot [
                    domain=1.96:4,
                    samples=100,
                    fill=red,
                    opacity=0.5,
                ] {exp(-x^2 / 2) / sqrt(2 * pi)} \closedcycle;
                \addlegendentry{Región Crítica Derecha}

                % Línea vertical en Z = -1.96
                \addplot[red, dashed] coordinates {(-1.96, 0) (-1.96, 0.1)};
                \node at (axis cs:-1.96,0.13) [anchor=north east, blue] {-1.96};

                % Línea vertical en Z = 1.96
                \addplot[red, dashed] coordinates {(1.96, 0) (1.96, 0.1)};
                \node at (axis cs:1.96,0.13) [anchor=north west, blue] {1.96};

                % Línea vertical en Z = -0.35
                \addplot[black, dashed] coordinates {(-0.35, 0) (-0.35, 0.15)};
                \node at (axis cs:-0.35,0.18) [anchor=north east] {-0.35};
            \end{axis}
        \end{tikzpicture}
        \caption{Gráfico de la distribución Z con regiones críticas.}
    \end{figure}   
   \[
    Z_{0.975} = 1.96, \quad Z_{0.025} = -1.96
    \]
    La región crítica es:
    \[
    RC = Z_k < -1.96 \quad \text{o} \quad Z_k > 1.96
    \]
  \item \textbf{Cálculo del estadístico:}
    Ahora calculamos el estadístico \(z\):
    \[
    Z_k = \frac{p_{\text{ma}} - p_{\text{ha}}}{\sqrt{P(1 - P) \left( \frac{1}{n_1} + \frac{1}{n_2} \right)}}
    \]
    \[
    Z_k = \frac{0.2262 - 0.2500}{\sqrt{0.2375(1 - 0.2375) \left( \frac{1}{84} + \frac{1}{76} \right)}} = \frac{-0.0238}{\sqrt{0.2375 \cdot 0.7625 \cdot \left( 0.0119 + 0.0132 \right)}}
    \]
    \[
    Z_k = \frac{-0.0238}{\sqrt{0.2375 \cdot 0.7625 \cdot 0.0251}} \approx -0.3500
    \]

  \item \textbf{Decisión:}
    El valor calculado de \( z \approx -0.3500 \) no está dentro de la región crítica (\(RC\)), por lo que no se rechaza la hipótesis nula \(H_0\).
    
  \item \textbf{Conclusión:}
    Con un nivel de significancia del 5\%, no hay suficiente evidencia para afirmar que las proporciones de estudiantes aprobados en matemáticas entre mujeres y hombres en las zonas rurales de Ayacucho son diferentes.
\end{enumerate}

\subsubsection*{Los hombres superan a las mujeres en el promedio general
por más de 15
puntos}\label{los-hombres-superan-a-las-mujeres-en-el-promedio-general-por-muxe1s-de-15-puntos}
\addcontentsline{toc}{subsubsection}{Los hombres superan a las mujeres
en el promedio general por más de 15 puntos}

Se desea determinar si los estudiantes hombres tienen un rendimiento
académico promedio en matemáticas superior en más de 15 puntos que el de
las estudiantes mujeres en zonas rurales de Ayacucho. Con un nivel de
significancia del 5\%, se cuenta con los siguientes datos muestrales:

\begin{enumerate}
    \item \textbf{Hipótesis nula y alternativa:}
    \[
    H_0: \mu_{\text{hombres}} - \mu_{\text{mujeres}} \leq 15
    \]
    \[
    H_1: \mu_{\text{hombres}} - \mu_{\text{mujeres}} > 15
    \]

   \item \textbf{Nivel de significancia:}
    \[
    \alpha = 0.05
    \]

   \item \textbf{Estadístico de prueba:}
    La fórmula del estadístico \( t \) para muestras independientes con varianzas iguales es:
    \[
    t = \frac{X_{\text{hombres}} - X_{\text{mujeres}} - (\mu_{\text{hombres}} - \mu_{\text{mujeres}})}{\sqrt{\frac{S_{\text{hombres}}^2}{n_{\text{hombres}}} + \frac{S_{\text{mujeres}}^2}{n_{\text{mujeres}}}}}
    \]
    donde:
    \[
    X_{\text{hombres}} = 553.2158, \quad X_{\text{mujeres}} = 538.5511, \quad n_{\text{hombres}} = 76, \quad n_{\text{mujeres}} = 84
    \]

   La desviación estándar combinada \( S_c \) se calcula como:
    \[
    S_c = \sqrt{\frac{(n_{\text{hombres}} - 1) S_{\text{hombres}}^2 + (n_{\text{mujeres}} - 1) S_{\text{mujeres}}^2}{n_{\text{hombres}} + n_{\text{mujeres}} - 2}}
    \]
    donde:
    \[
    S_{\text{hombres}} = 76.7082, \quad S_{\text{mujeres}} = 77.12865
    \]

   Reemplazando los valores:
    \[
    S_c = \sqrt{\frac{(84 - 1) (77.12865)^2 + (76 - 1) (76.70822)^2}{84 + 76 - 2}} = 76.93
    \]

   Ahora hallamos \( t \):
    \[
    t = \frac{553.2158 - 538.5511 - 15}{\sqrt{\frac{76.93^2}{84} + \frac{76.93^2}{76}}} = \frac{553.2158 - 538.5511 - 15}{12.1789} = -0.027
    \]

  \item \textbf{Región crítica:}
    \begin{figure}[ht]
    \centering
    \begin{tikzpicture}
        \begin{axis}[
            domain=-4:4,
            samples=200,
            xlabel={Valores de \( t \)},
            ylabel={Densidad de probabilidad},
            ymin=0,
            ymax=0.45,
            axis lines=left,
            legend pos=north east,
            title={Distribución \( t \) de student con Región Crítica (una cola)}
        ]
            % Curva de la distribución t de student
            \addplot[blue, thick] {exp(-x^2 / 2) / sqrt(2 * pi)};
            \addlegendentry{Distribución \( t \)}

            % Región crítica (x >= 1.645)
            \addplot [
                domain=1.645:4,
                samples=100,
                fill=red,
                opacity=0.5,
            ] {exp(-x^2 / 2) / sqrt(2 * pi)} \closedcycle;
            \addlegendentry{Región Crítica}

            % Línea vertical en valor crítico (1.645)
            \addplot[brown, dashed, thick] coordinates {(1.645, 0) (1.645, 0.2)};
            \node at (axis cs:1.645,0.2) [anchor=north west, brown] {\( t = 1.645 \)};

            % Línea vertical en \( t \) calculado (-0.027)
            \addplot[green, dashed, thick] coordinates {(-0.027, 0) (-0.027, 0.13)};
            \node at (axis cs:-0.010,0.13) [anchor=north east, black] {\( t_{k} = -0.027 \)};
        \end{axis}
    \end{tikzpicture}
    \caption{Distribución \( t \) con región crítica y estadístico calculado.}
   \end{figure}
    La región crítica se define como:
    \[
    t_{0.05, 158} = 1.645
    \]
    \[
    RC: t_k < -1.645 \quad \text{o} \quad t_k > 1.645
    \]

    \item \textbf{Decisión:}
    Como \( t_k = -0.027 \) no está en la región crítica, no se rechaza la hipótesis nula \( H_0 \).

    \item \textbf{Conclusión:}
    Con un nivel de significancia del 5\%, no hay suficiente evidencia para afirmar que las medias de las   notas de los estudiantes hombres superan en más de 15 puntos el promedio de las estudiantes mujeres en matemáticas en las zonas rurales de Ayacucho.
\end{enumerate}

\section*{Resultados}\label{resultados}
\addcontentsline{toc}{section}{Resultados}

\subsection*{Objetivos Generales}\label{objetivos-generales}
\addcontentsline{toc}{subsection}{Objetivos Generales}

Determinar si existe una diferencia significativa en el rendimiento
académico en matemáticas entre hombres y mujeres en zonas rurales de
Ayacucho.

\begin{itemize}
  \item \textbf{Resultado:}
    \begin{itemize}
        \item La media de las notas en matemáticas de las estudiantes mujeres es de 538.55 con una desviación estándar de 77.13.
        \item La media de las notas en matemáticas de los estudiantes hombres es de 553.22 con una desviación estándar de 76.71.
        \item El estadístico \( t \) calculado es de -1.2.
        \item El valor crítico para un nivel de significancia del 5\% es \( \pm 1.97 \).
    \end{itemize}
    
  \item \textbf{Decisión:}
    Como -1.2 no está en la región crítica (\( t < -1.97 \) o \( t > 1.97 \)), no se rechaza la hipótesis nula (\( p > 0.05 \)).
\end{itemize}

\subsection*{Objetivos Específicos}\label{objetivos-especuxedficos-1}
\addcontentsline{toc}{subsection}{Objetivos Específicos}

\begin{itemize}
  \item \textbf{Objetivo Específico 1:} Comparar si el promedio de las notas en matemáticas de los estudiantes hombres es mayor al promedio de las estudiantes mujeres en zonas rurales de Ayacucho.
    \begin{itemize}
        \item La media de los hombres es de 553.22 y la de las mujeres es de 538.55.
        \item El estadístico \( t \) calculado es de -1.2.
        \item No se rechaza la hipótesis nula, indicando que no hay suficiente evidencia para afirmar que los hombres tienen un promedio mayor al de las mujeres.
    \end{itemize}
    
  \item \textbf{Objetivo Específico 2:} Determinar si existen diferencias en las proporciones de aprobados en matemáticas entre mujeres y hombres.
    \begin{itemize}
        \item Proporción de aprobadas mujeres: \( \frac{19}{84} \approx 0.2262 \).
        \item Proporción de aprobados hombres: \( \frac{19}{76} \approx 0.2500 \).
        \item El estadístico \( z \) calculado es de -0.35.
        \item Como -0.35 no está en la región crítica (\(-1.96 < z < 1.96\)), no se rechaza la hipótesis nula.
    \end{itemize}
    
  \item \textbf{Objetivo Específico 3:} Evaluar si el promedio de los hombres supera en más de 15 puntos al promedio de las mujeres.
    \begin{itemize}
        \item La diferencia entre las medias muestrales es de 14.67 puntos (\(553.22 - 538.55\)).
        \item El estadístico \( t \) calculado de la prueba es de -0.027 y no pertenece a la región crítica.
        \item No se rechaza la hipótesis nula.
    \end{itemize}
\end{itemize}

\section*{Conclusiones}\label{conclusiones}
\addcontentsline{toc}{section}{Conclusiones}

\begin{enumerate}
  \item \textbf{Conclusión del Objetivo General:}
    No se encontró una diferencia estadísticamente significativa en el rendimiento académico promedio en matemáticas entre hombres y mujeres en zonas rurales de Ayacucho. La diferencia observada puede atribuirse al azar.
    
  \item \textbf{Conclusión del Objetivo Específico 1:}
    No hay suficiente evidencia para afirmar que los hombres tienen un promedio de notas en matemáticas mayor que las mujeres en zonas rurales de Ayacucho.
    
  \item \textbf{Conclusión del Objetivo Específico 2:}
    Con un nivel de significancia del 5%, no hay suficiente evidencia para afirmar que las proporciones de estudiantes aprobados en matemáticas entre mujeres y hombres en las zonas rurales de Ayacucho son diferentes. Las tasas de aprobación son similares para ambos géneros.
    
  \item \textbf{Conclusión del Objetivo Específico 3:}
    Con una significancia del 5% no podemos afirmar que el promedio de las notas de los hombres en el curso de matemáticas supera en más de 15 puntos al promedio de las mujeres.
\end{enumerate}

\newpage

\section*{Referencias}\label{referencias}
\addcontentsline{toc}{section}{Referencias}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-cohen1988statistical}
Cohen, J. (1988). \emph{Statistical power analysis for the behavioral
sciences} (2nd ed.). Lawrence Erlbaum Associates, New York.

\bibitem[\citeproctext]{ref-cueto2004factores}
Cueto, S. (2004). \emph{Factores predictivos del rendimiento educativo
en el per{ú}}.

\bibitem[\citeproctext]{ref-field2013discovering}
Field, A. (2013). \emph{Discovering statistics using {IBM SPSS}
statistics} (4th ed.). SAGE Publications, London.

\bibitem[\citeproctext]{ref-inei2021brechas}
Instituto Nacional de Estadística e Informática. (2021). \emph{Per{ú}:
Brechas de g{é}nero, 2021}.

\bibitem[\citeproctext]{ref-larepublica_2021}
La República. (2021). \emph{Ni{ñ}as de zonas rurales son las m{á}s
afectadas por la desigualdad educativa}.

\bibitem[\citeproctext]{ref-UNICEF}
Perú, UNICEF. R. en. (2016). \emph{Estado mundial de la infancia 2016:
Acabar con las inequidades para brindarle oportunidades justas a toda la
niñez}. UNICEF.

\bibitem[\citeproctext]{ref-tarea2021proyecto}
Tarea.org.pe. (2021). \emph{El proyecto educativo regional de ayacucho:
Rutas y desaf{í}os}.

\bibitem[\citeproctext]{ref-datatab_2024}
Team, D. (2024). \emph{Prueba t para muestras independientes}.

\bibitem[\citeproctext]{ref-unicef_2021}
UNICEF. (2021). \emph{Efectos de la desigualdad de g{é}nero en la
educaci{ó}n de las ni{ñ}as y adolescentes}.

\end{CSLReferences}

\end{document}
